// Email Provider Catalog Seed Data
// Based on 17hats provider list with comprehensive IMAP/SMTP settings

export const EMAIL_PROVIDER_SEEDS = [
  {
    code: "google",
    displayName: "Google: GSuite, Gmail",
    authType: "oauth",
    imapHost: "imap.gmail.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.gmail.com",
    smtpPort: 465,
    smtpSecure: true,
    helpBlurb: "Use Google OAuth for best security. If using password auth, enable 2FA and create an app password. IMAP: imap.gmail.com:993 (SSL), SMTP: smtp.gmail.com:465 (SSL).",
    isActive: true
  },
  {
    code: "microsoft",
    displayName: "Office 365",
    authType: "oauth",
    imapHost: "outlook.office365.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.office365.com",
    smtpPort: 587,
    smtpSecure: false,
    helpBlurb: "Preferred: Microsoft OAuth (Graph API). IMAP: outlook.office365.com:993 (SSL), SMTP: smtp.office365.com:587 (STARTTLS).",
    isActive: true
  },
  {
    code: "hotmail",
    displayName: "Hotmail/MSN/Outlook/Live.com",
    authType: "imap_smtp",
    imapHost: "outlook.office365.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.office365.com",
    smtpPort: 587,
    smtpSecure: false,
    helpBlurb: "Use your Microsoft account with IMAP/SMTP. Password auth supported. IMAP: outlook.office365.com:993 (SSL), SMTP: smtp.office365.com:587 (STARTTLS).",
    isActive: true
  },
  {
    code: "icloud",
    displayName: "iCloud / Mac.com / Me.com",
    authType: "imap_smtp",
    imapHost: "imap.mail.me.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.mail.me.com",
    smtpPort: 587,
    smtpSecure: false,
    helpBlurb: "Requires an Apple **app-specific password** generated in Apple ID settings. IMAP: imap.mail.me.com:993 (SSL), SMTP: smtp.mail.me.com:587 (STARTTLS).",
    isActive: true
  },
  {
    code: "yahoo",
    displayName: "Yahoo!",
    authType: "imap_smtp",
    imapHost: "imap.mail.yahoo.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.mail.yahoo.com",
    smtpPort: 465,
    smtpSecure: true,
    helpBlurb: "Enable 2FA and generate an **app password**. IMAP: imap.mail.yahoo.com:993 (SSL), SMTP: smtp.mail.yahoo.com:465 (SSL).",
    isActive: true
  },
  {
    code: "godaddy_o365",
    displayName: "GoDaddy: Office365",
    authType: "oauth",
    imapHost: "outlook.office365.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.office365.com",
    smtpPort: 587,
    smtpSecure: false,
    helpBlurb: "Same as Office 365; OAuth works if enabled on your tenant. IMAP: outlook.office365.com:993 (SSL), SMTP: smtp.office365.com:587 (STARTTLS).",
    isActive: true
  },
  {
    code: "godaddy_workspace",
    displayName: "GoDaddy: Workspace",
    authType: "imap_smtp",
    imapHost: "imap.secureserver.net",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtpout.secureserver.net",
    smtpPort: 465,
    smtpSecure: true,
    helpBlurb: "Use full email as username; SSL required on many plans. IMAP: imap.secureserver.net:993 (SSL), SMTP: smtpout.secureserver.net:465 (SSL).",
    isActive: true
  },
  {
    code: "bluehost",
    displayName: "BlueHost",
    authType: "imap_smtp",
    imapHost: "mail.yourdomain.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "mail.yourdomain.com",
    smtpPort: 465,
    smtpSecure: true,
    helpBlurb: "cPanel mail; replace 'mail.yourdomain.com' with your actual domain. IMAP: mail.yourdomain.com:993 (SSL), SMTP: mail.yourdomain.com:465 (SSL).",
    isActive: true
  },
  {
    code: "siteground",
    displayName: "SiteGround",
    authType: "imap_smtp",
    imapHost: "mail.yourdomain.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "mail.yourdomain.com",
    smtpPort: 465,
    smtpSecure: true,
    helpBlurb: "Use Site Tools mail settings. Replace 'mail.yourdomain.com' with your domain. IMAP: mail.yourdomain.com:993 (SSL), SMTP: mail.yourdomain.com:465 (SSL).",
    isActive: true
  },
  {
    code: "ionos",
    displayName: "1and1 / IONOS",
    authType: "imap_smtp",
    imapHost: "imap.ionos.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.ionos.com",
    smtpPort: 465,
    smtpSecure: true,
    helpBlurb: "May require SSL and full email username. IMAP: imap.ionos.com:993 (SSL), SMTP: smtp.ionos.com:465 (SSL).",
    isActive: true
  },
  {
    code: "att",
    displayName: "AT&T",
    authType: "imap_smtp",
    imapHost: "imap.mail.att.net",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.mail.att.net",
    smtpPort: 465,
    smtpSecure: true,
    helpBlurb: "Legacy providers may need app passwords. IMAP: imap.mail.att.net:993 (SSL), SMTP: smtp.mail.att.net:465 (SSL).",
    isActive: true
  },
  {
    code: "bellsouth",
    displayName: "BellSouth",
    authType: "imap_smtp",
    imapHost: "imap.mail.att.net",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.mail.att.net",
    smtpPort: 465,
    smtpSecure: true,
    helpBlurb: "Legacy AT&T settings. IMAP: imap.mail.att.net:993 (SSL), SMTP: smtp.mail.att.net:465 (SSL).",
    isActive: true
  },
  {
    code: "cox",
    displayName: "Cox Business",
    authType: "imap_smtp",
    imapHost: "imap.cox.net",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.cox.net",
    smtpPort: 465,
    smtpSecure: true,
    helpBlurb: "IMAP/SMTP per Cox documentation. IMAP: imap.cox.net:993 (SSL), SMTP: smtp.cox.net:465 (SSL).",
    isActive: true
  },
  {
    code: "sbcglobal",
    displayName: "SBC Global",
    authType: "imap_smtp",
    imapHost: "imap.mail.att.net",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.mail.att.net",
    smtpPort: 465,
    smtpSecure: true,
    helpBlurb: "Legacy AT&T domain. IMAP: imap.mail.att.net:993 (SSL), SMTP: smtp.mail.att.net:465 (SSL).",
    isActive: true
  },
  {
    code: "sky",
    displayName: "Sky",
    authType: "imap_smtp",
    imapHost: "imap.tools.sky.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.tools.sky.com",
    smtpPort: 465,
    smtpSecure: true,
    helpBlurb: "Use Sky tools mail settings. IMAP: imap.tools.sky.com:993 (SSL), SMTP: smtp.tools.sky.com:465 (SSL).",
    isActive: true
  },
  {
    code: "aol",
    displayName: "AOL",
    authType: "imap_smtp",
    imapHost: "imap.aol.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.aol.com",
    smtpPort: 465,
    smtpSecure: true,
    helpBlurb: "App password recommended. IMAP: imap.aol.com:993 (SSL), SMTP: smtp.aol.com:465 (SSL).",
    isActive: true
  },
  {
    code: "aim",
    displayName: "AIM",
    authType: "imap_smtp",
    imapHost: "imap.aol.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.aol.com",
    smtpPort: 465,
    smtpSecure: true,
    helpBlurb: "Legacy AOL settings. IMAP: imap.aol.com:993 (SSL), SMTP: smtp.aol.com:465 (SSL).",
    isActive: true
  },
  {
    code: "zoho",
    displayName: "Zoho",
    authType: "imap_smtp",
    imapHost: "imap.zoho.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.zoho.com",
    smtpPort: 465,
    smtpSecure: true,
    helpBlurb: "May require app password. IMAP: imap.zoho.com:993 (SSL), SMTP: smtp.zoho.com:465 (SSL).",
    isActive: true
  },
  {
    code: "other",
    displayName: "Other…",
    authType: "imap_smtp",
    imapHost: null,
    imapPort: null,
    imapSecure: null,
    smtpHost: null,
    smtpPort: null,
    smtpSecure: null,
    helpBlurb: "Enter your custom IMAP/SMTP hostnames, ports, and SSL settings manually.",
    isActive: true
  }
];
