import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Sparkles, Loader2, MessageSquare, ListTodo } from "lucide-react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";

interface EmailSummary {
  id: string;
  summary: string;
  model: string;
  createdAt: string;
}

interface EmailDraft {
  id: string;
  draftContent: string;
  model: string;
  createdAt: string;
}

interface ActionItem {
  id: string;
  actionText: string;
  dueDate?: string;
  priority: 'high' | 'medium' | 'low';
  status: string;
  createdAt: string;
}

interface SummarizeThreadButtonProps {
  threadId: string;
}

export function SummarizeThreadButton({ threadId }: SummarizeThreadButtonProps) {
  const [showSummary, setShowSummary] = useState(false);
  const { toast } = useToast();

  const summarizeMutation = useMutation({
    mutationFn: async () => {
      const response = await apiRequest('POST', `/api/ai/threads/${threadId}/summarize`);
      const data = await response.json();
      return data as EmailSummary;
    },
    onSuccess: () => {
      setShowSummary(true);
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to generate summary",
        variant: "destructive",
      });
    },
  });

  const summary = summarizeMutation.data;

  return (
    <>
      <Button
        variant="outline"
        size="sm"
        onClick={() => summarizeMutation.mutate()}
        disabled={summarizeMutation.isPending}
        data-testid="button-summarize-thread"
      >
        {summarizeMutation.isPending ? (
          <Loader2 className="h-4 w-4 mr-2 animate-spin" />
        ) : (
          <Sparkles className="h-4 w-4 mr-2" />
        )}
        Summarize
      </Button>

      <Dialog open={showSummary} onOpenChange={setShowSummary}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>AI Summary</DialogTitle>
            <DialogDescription>
              Quick summary of this email conversation
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            {summary ? (
              <>
                <p className="text-sm leading-relaxed" data-testid="text-summary">
                  {summary.summary}
                </p>
                <div className="text-xs text-muted-foreground">
                  Generated by {summary.model}
                </div>
              </>
            ) : (
              <div className="flex items-center justify-center py-8">
                <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
              </div>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}

interface DraftReplyButtonProps {
  emailId: string;
  onDraftGenerated?: (draft: string) => void;
}

export function DraftReplyButton({ emailId, onDraftGenerated }: DraftReplyButtonProps) {
  const [showDraft, setShowDraft] = useState(false);
  const { toast } = useToast();

  const draftMutation = useMutation({
    mutationFn: async () => {
      const response = await apiRequest('POST', `/api/ai/emails/${emailId}/draft-reply`);
      const data = await response.json();
      return data as EmailDraft;
    },
    onSuccess: (data) => {
      setShowDraft(true);
      if (onDraftGenerated) {
        onDraftGenerated(data.draftContent);
      }
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to generate draft",
        variant: "destructive",
      });
    },
  });

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({
      title: "Copied!",
      description: "Draft copied to clipboard",
    });
  };

  return (
    <>
      <Button
        variant="outline"
        size="sm"
        onClick={() => draftMutation.mutate()}
        disabled={draftMutation.isPending}
        data-testid="button-draft-reply"
      >
        {draftMutation.isPending ? (
          <Loader2 className="h-4 w-4 mr-2 animate-spin" />
        ) : (
          <MessageSquare className="h-4 w-4 mr-2" />
        )}
        Draft Reply
      </Button>

      <Dialog open={showDraft} onOpenChange={setShowDraft}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>AI-Generated Reply</DialogTitle>
            <DialogDescription>
              Review and customize this suggested response
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            {draftMutation.data ? (
              <>
                <Textarea
                  value={draftMutation.data.draftContent}
                  readOnly
                  className="min-h-[200px] font-mono text-sm"
                  data-testid="textarea-draft-content"
                />
                <div className="flex items-center justify-between">
                  <div className="text-xs text-muted-foreground">
                    Generated by {draftMutation.data.model}
                  </div>
                  <Button
                    variant="secondary"
                    size="sm"
                    onClick={() => copyToClipboard(draftMutation.data!.draftContent)}
                    data-testid="button-copy-draft"
                  >
                    Copy to Clipboard
                  </Button>
                </div>
              </>
            ) : (
              <div className="flex items-center justify-center py-8">
                <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
              </div>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}

interface ExtractActionsButtonProps {
  emailId: string;
}

export function ExtractActionsButton({ emailId }: ExtractActionsButtonProps) {
  const [showActions, setShowActions] = useState(false);
  const { toast } = useToast();

  const extractMutation = useMutation({
    mutationFn: async () => {
      const response = await apiRequest('POST', `/api/ai/emails/${emailId}/extract-actions`);
      const data = await response.json();
      return data as ActionItem[];
    },
    onSuccess: (data) => {
      setShowActions(true);
      if (data.length === 0) {
        toast({
          title: "No action items found",
          description: "This email doesn't contain any actionable tasks",
        });
      }
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to extract action items",
        variant: "destructive",
      });
    },
  });

  const updateStatusMutation = useMutation({
    mutationFn: async ({ id, status }: { id: string; status: string }) => {
      await apiRequest('PATCH', `/api/ai/actions/${id}/status`, { status });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [`/api/ai/emails/${emailId}/extract-actions`] });
    },
  });

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'high': return 'destructive';
      case 'medium': return 'default';
      case 'low': return 'secondary';
      default: return 'outline';
    }
  };

  return (
    <>
      <Button
        variant="outline"
        size="sm"
        onClick={() => extractMutation.mutate()}
        disabled={extractMutation.isPending}
        data-testid="button-extract-actions"
      >
        {extractMutation.isPending ? (
          <Loader2 className="h-4 w-4 mr-2 animate-spin" />
        ) : (
          <ListTodo className="h-4 w-4 mr-2" />
        )}
        Extract Actions
      </Button>

      <Dialog open={showActions} onOpenChange={setShowActions}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Action Items</DialogTitle>
            <DialogDescription>
              Tasks and to-dos extracted from this email
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            {extractMutation.data && extractMutation.data.length > 0 ? (
              <div className="space-y-3">
                {extractMutation.data.map((action) => (
                  <div
                    key={action.id}
                    className="flex items-start gap-3 p-3 border rounded-lg"
                    data-testid={`action-item-${action.id}`}
                  >
                    <Checkbox
                      checked={action.status === 'completed'}
                      onCheckedChange={(checked) => {
                        updateStatusMutation.mutate({
                          id: action.id,
                          status: checked ? 'completed' : 'pending'
                        });
                      }}
                      data-testid={`checkbox-action-${action.id}`}
                    />
                    <div className="flex-1 space-y-1">
                      <p className={`text-sm ${action.status === 'completed' ? 'line-through text-muted-foreground' : ''}`}>
                        {action.actionText}
                      </p>
                      <div className="flex items-center gap-2">
                        <Badge variant={getPriorityColor(action.priority) as any}>
                          {action.priority}
                        </Badge>
                        {action.dueDate && (
                          <span className="text-xs text-muted-foreground">
                            Due: {new Date(action.dueDate).toLocaleDateString()}
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : extractMutation.data && extractMutation.data.length === 0 ? (
              <p className="text-sm text-muted-foreground text-center py-8">
                No action items found in this email
              </p>
            ) : (
              <div className="flex items-center justify-center py-8">
                <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
              </div>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}

interface AIComposeButtonProps {
  onDraftGenerated: (draft: string, subject?: string) => void;
  projectContext?: string;
  contactName?: string;
  onBeforeCompose?: (proceedFn: () => void) => void;
}

export function AIComposeButton({ onDraftGenerated, projectContext, contactName, onBeforeCompose }: AIComposeButtonProps) {
  const [showDialog, setShowDialog] = useState(false);
  const [instructions, setInstructions] = useState('');
  const { toast } = useToast();

  const handleClick = () => {
    if (onBeforeCompose) {
      onBeforeCompose(() => setShowDialog(true));
    } else {
      setShowDialog(true);
    }
  };

  const composeMutation = useMutation({
    mutationFn: async () => {
      const response = await apiRequest('POST', '/api/ai/compose-email', {
        instructions,
        projectContext,
        contactName
      });
      const data = await response.json();
      return data as { draft: string; subject?: string; model: string; stylePersonalized: boolean };
    },
    onSuccess: (data) => {
      onDraftGenerated(data.draft, data.subject);
      setShowDialog(false);
      setInstructions('');
      toast({
        title: data.stylePersonalized ? "✨ Draft using your writing style!" : "Draft generated!",
        description: data.stylePersonalized 
          ? "AI learned from your sent emails to match your tone" 
          : "Send a few emails to teach AI your writing style",
      });
    },
    onError: (error: Error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to generate draft",
        variant: "destructive",
      });
    },
  });

  return (
    <>
      <Button
        variant="outline"
        size="sm"
        onClick={handleClick}
        data-testid="button-ai-compose"
      >
        <Sparkles className="h-4 w-4 mr-2" />
        AI Compose
      </Button>

      <Dialog open={showDialog} onOpenChange={setShowDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>AI Email Assistant</DialogTitle>
            <DialogDescription>
              Tell the AI what you want to write, and it will create a draft for you
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">What would you like to write?</label>
              <Textarea
                value={instructions}
                onChange={(e) => setInstructions(e.target.value)}
                placeholder="E.g., 'Write a follow-up email thanking them for the meeting and confirming next steps' or 'Ask about project timeline and budget'"
                className="min-h-[120px]"
                data-testid="textarea-ai-instructions"
              />
            </div>
            <div className="flex justify-end gap-2">
              <Button
                variant="outline"
                onClick={() => setShowDialog(false)}
                data-testid="button-cancel-ai-compose"
              >
                Cancel
              </Button>
              <Button
                onClick={() => composeMutation.mutate()}
                disabled={!instructions.trim() || composeMutation.isPending}
                data-testid="button-generate-ai-compose"
              >
                {composeMutation.isPending ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4 mr-2" />
                    Generate Draft
                  </>
                )}
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
